name: nima_comunity_member_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_screenutil: ^5.8.4
  get: ^4.6.5
  table_calendar: ^3.0.9
  sms_autofill: ^2.3.0
  alt_sms_autofill: ^1.0.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  image_picker: ^1.0.0
  cached_network_image: ^3.2.3
  intl_phone_field: ^3.2.0
  agora_uikit: ^1.3.4
  shortid: ^0.1.2
  permission_handler: any

dependency_overrides:
  test_api: 0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/segoe-fonts/Segoe UI Bold.ttf
          weight: 600
        - asset: assets/segoe-fonts/Segoe UI.ttf
          weight: 400
